print("Welcome to Knockout")
print("Here is the set of rules and instrctions: ")
print("You can use WASD or the arrow keys to move you helicopter")
print("Three lives will be given to all players")
print("Special powers will float through the air to be collected)
print("Running into walls will make you loose a life")
print("This is a single player game")
